language: python
sudo: false
python:
  - 2.7
  - 3.6
  - 3.7
env:
    - AWS_DEFAULT_REGION=eu-west-1 AWS_ACCESS_KEY_ID=dummy AWS_SECRET_ACCESS_KEY=dummy BOTO_CONFIG=/dev/null
install:
  - travis_retry pip install -r requirements-dev.txt
script:
  - nosetests
after_success:
  - nosetests --with-coverage --cover-erase --cover-html --cover-package=ssm_cache
  - coveralls
