language: python
sudo: false
python:
  - 2.7
  - 3.6
install:
  - travis_retry pip install -r requirements-dev.txt
script:
  - nosetests
after_success:
  - nosetests --with-coverage --cover-erase --cover-html --cover-package=ssm_cache